FROM kartoza/geoserver:2.18.0

ARG DB_HOST=

ARG PORT=

ARG DB_NAME=

ARG USER=

ARG PGPASSWORD=

ENV DB_HOST ${DB_HOST}

ENV PORT ${PORT}

ENV DB_NAME ${DB_NAME}

ENV USER ${USER}

ENV PGPASSWORD ${PGPASSWORD}

USER root

COPY . /daaas-geo

WORKDIR /daaas-geo/scripts

RUN chmod u+x dl-data.sh

RUN chmod u+x import.sh

RUN sh dl-data.sh

RUN sh import.sh

RUN wget -P /usr/local/tomcat/webapps/geoserver/WEB-INF/lib \ 
    https://sourceforge.net/projects/geoserver/files/GeoServer/2.18.0/extensions/geoserver-2.18.0-wps-plugin.zip

RUN wget -P /usr/local/tomcat/webapps/geoserver/WEB-INF/lib \ 
    https://sourceforge.net/projects/geoserver/files/GeoServer/2.18.0/extensions/geoserver-2.18.0-csw-plugin.zip

RUN wget -P /usr/local/tomcat/webapps/geoserver/WEB-INF/lib \
    https://sourceforge.net/projects/geoserver/files/GeoServer/2.18.0/extensions/geoserver-2.18.0-vectortiles-plugin.zip

RUN unzip -o /usr/local/tomcat/webapps/geoserver/WEB-INF/lib/geoserver-2.18.0-wps-plugin.zip

RUN unzip -o /usr/local/tomcat/webapps/geoserver/WEB-INF/lib/geoserver-2.18.0-csw-plugin.zip

RUN unzip -o /usr/local/tomcat/webapps/geoserver/WEB-INF/lib/geoserver-2.18.0-vectortiles-plugin.zip
    
